<a href="https://colab.research.google.com/github/tekinmuhammed/ML-Proje/blob/main/eeg_eye_state.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from scipy.io import arff
import numpy as np
import matplotlib.pyplot as plt
data = arff.loadarff('EEG Eye State.arff')
train= pd.DataFrame(data[0])
train.head(6656)

AF3       F7       F3      FC5       T7       P7       O1       O2  \
0     4329.23  4009.23  4289.23  4148.21  4350.26  4586.15  4096.92  4641.03   
1     4324.62  4004.62  4293.85  4148.72  4342.05  4586.67  4097.44  4638.97   
2     4327.69  4006.67  4295.38  4156.41  4336.92  4583.59  4096.92  4630.26   
3     4328.72  4011.79  4296.41  4155.90  4343.59  4582.56  4097.44  4630.77   
4     4326.15  4011.79  4292.31  4151.28  4347.69  4586.67  4095.90  4627.69   
...       ...      ...      ...      ...      ...      ...      ...      ...   
6651  4407.69  4047.69  4284.10  4134.36  4329.74  4610.77  4062.05  4600.00   
6652  4408.72  4051.79  4281.03  4134.87  4325.13  4612.31  4058.46  4591.79   
6653  4408.72  4053.85  4279.49  4132.82  4323.59  4606.15  4055.90  4595.38   
6654  4410.77  4055.90  4281.54  4133.33  4326.15  4602.56  4056.92  4607.18   
6655  4407.69  4047.18  4277.95  4125.13  4323.08  4604.10  4055.90  4610.26   

           P8       T8      FC6       F4       F8      AF4 eyeDetection  
0     4222.05  4238.46  4211.28  4280.51  4635.90  4393.85         b'0'  
1     4210.77  4226.67  4207.69  4279.49  4632.82  4384.10         b'0'  
2     4207.69  4222.05  4206.67  4282.05  4628.72  4389.23         b'0'  
3     4217.44  4235.38  4210.77  4287.69  4632.31  4396.41         b'0'  
4     4210.77  4244.10  4212.82  4288.21  4632.82  4398.46         b'0'  
...       ...      ...      ...      ...      ...      ...          ...  
6651  4181.54  4228.21  4237.44  4307.18  4672.82  4472.31         b'0'  
6652  4178.46  4233.33  4231.28  4304.10  4662.05  4469.74         b'0'  
6653  4194.36  4241.03  4230.26  4304.62  4663.59  4474.36         b'1'  
6654  4203.08  4241.03  4236.92  4305.64  4673.85  4475.38         b'1'  
6655  4194.36  4237.44  4238.97  4303.08  4674.87  4472.31         b'1'  

[6656 rows x 15 columns]

In [ ]:
X = train.iloc[:, :-1].values
y = train.iloc[:, -1].values

In [ ]:
print(X)

[[4329.23 4009.23 4289.23 ... 4280.51 4635.9  4393.85]
 [4324.62 4004.62 4293.85 ... 4279.49 4632.82 4384.1 ]
 [4327.69 4006.67 4295.38 ... 4282.05 4628.72 4389.23]
 ...
 [4277.44 3990.77 4246.67 ... 4257.95 4591.79 4339.49]
 [4284.62 3991.79 4251.28 ... 4267.18 4596.41 4350.77]
 [4287.69 3997.44 4260.   ... 4274.36 4597.95 4350.77]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:-1])
X[:, 1:-1] = imputer.transform(X[:, 1:-1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X)

[[4329.23 4009.23 4289.23 ... 4280.51 4635.9  4393.85]
 [4324.62 4004.62 4293.85 ... 4279.49 4632.82 4384.1 ]
 [4327.69 4006.67 4295.38 ... 4282.05 4628.72 4389.23]
 ...
 [4277.44 3990.77 4246.67 ... 4257.95 4591.79 4339.49]
 [4284.62 3991.79 4251.28 ... 4267.18 4596.41 4350.77]
 [4287.69 3997.44 4260.   ... 4274.36 4597.95 4350.77]]


In [ ]:
print(X_train)

[[4284.1  3990.26 4267.18 ... 4289.74 4624.62 4362.05]
 [4301.03 3982.56 4272.82 ... 4287.18 4588.72 4364.1 ]
 [4298.97 4050.26 4277.44 ... 4287.69 4606.67 4351.28]
 ...
 [4284.1  3982.56 4264.62 ... 4258.97 4594.36 4354.87]
 [4361.03 4062.05 4325.64 ... 4330.26 4663.59 4411.28]
 [4276.92 4001.54 4256.92 ... 4274.36 4588.72 4333.33]]


In [ ]:
print(X_test)

[[4270.77 4017.44 4258.97 ... 4286.15 4617.95 4342.05]
 [4336.92 4034.36 4300.   ... 4305.13 4626.15 4392.31]
 [4298.46 3992.82 4264.1  ... 4289.74 4599.49 4380.  ]
 ...
 [4294.87 3995.38 4272.31 ... 4278.46 4587.69 4348.72]
 [4318.97 4009.23 4278.97 ... 4291.79 4620.51 4389.74]
 [4288.21 3984.1  4262.56 ... 4261.03 4592.31 4355.38]]


In [ ]:
print(y_train)

[0 1 0 ... 0 0 0]


In [ ]:
print(y_test)

[1 0 0 ... 1 1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.01532985 -0.41043601  0.06680816 ...  0.27767273  0.00525018
  -0.00898727]
 [-0.00925282 -0.57129895  0.19027327 ...  0.21121715 -0.02132655
  -0.00867187]
 [-0.00999226  0.84304145  0.29140958 ...  0.22445635 -0.00803818
  -0.01064428]
 ...
 [-0.01532985 -0.57129895  0.01076726 ... -0.52109219 -0.01715126
  -0.01009194]
 [ 0.01228419  1.08934977  1.34655467 ...  1.32953997  0.03409962
  -0.00141301]
 [-0.01790711 -0.17478225 -0.15779326 ... -0.12157994 -0.02132655
  -0.01340597]]


In [ ]:
print(X_test)

[[-2.01146504e-02  1.57389275e-01 -1.12916761e-01 ...  1.84479164e-01
   3.12385373e-04 -1.20643605e-02]
 [ 3.62989876e-03  5.10869919e-01  7.85270022e-01 ...  6.77184992e-01
   6.38283466e-03 -4.33162883e-03]
 [-1.01753221e-02 -3.56954309e-01 -6.16049063e-04 ...  2.77672732e-01
  -1.33535285e-02 -6.22557883e-03]
 ...
 [-1.14639530e-02 -3.03472604e-01  1.79108871e-01 ... -1.51471694e-02
  -2.20890531e-02 -1.10381504e-02]
 [-2.81325554e-03 -1.41282236e-02  3.24902778e-01 ...  3.30889115e-01
   2.20755003e-03 -4.72703513e-03]
 [-1.38545606e-02 -5.39126366e-01 -3.43281535e-02 ... -4.67616220e-01
  -1.86688731e-02 -1.00134788e-02]]


MULTİPLE LİNEAR REGRESSİON


In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0.36 1.  ]
 [0.45 0.  ]
 [0.55 0.  ]
 ...
 [0.54 1.  ]
 [0.58 1.  ]
 [0.49 1.  ]]


Logistic Regression


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 0]
 [1 0]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1236  389]
 [ 869  502]]


0.5801068090787717

K NEAREST NEIGHBOURS

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513  112]
 [ 149 1222]]


0.9128838451268357

SUPPORT VECTOR MACHİNE

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1439  186]
 [ 992  379]]


0.6068090787716955

KERNEL - SVM

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 1]
 [0 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1450  175]
 [ 677  694]]


0.7156208277703605

NAİVE BAYES


In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 514 1111]
 [ 357 1014]]


0.5100133511348465

DECISION TREE CLASSIFICATION

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1387  238]
 [ 269 1102]]


0.8307743658210948

RANDOM FOREST CLASSIFICATION

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1548   77]
 [ 239 1132]]


0.8945260347129506